#!/usr/bin/env python3
"""Create wedding place cards (席札) as a LibreOffice-editable .pptx and PDF.

Reads names from a CSV (generated by extract_guests.py) or a plain text file
(one name per line), and produces A4-landscape pages with 8 cards each (2x4).
"""

import argparse
import csv
import math
import subprocess
import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Mm, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

# --- Layout constants ---
A4_WIDTH = 297.0   # mm (landscape)
A4_HEIGHT = 210.0   # mm (landscape)
COLS = 2
ROWS = 4
CARDS_PER_PAGE = COLS * ROWS
CARD_WIDTH = A4_WIDTH / COLS    # 148.5mm
CARD_HEIGHT = A4_HEIGHT / ROWS  # 52.5mm

# --- Style defaults ---
FONT_NAME = "Noto Serif CJK JP"
WELCOME_TEXT = "welcome"
DATE_TEXT = "April 19, 2026"
WELCOME_FONT_SIZE = Pt(18)
DATE_FONT_SIZE = Pt(14)
NAME_FONT_SIZES = {6: Pt(28), 10: Pt(24)}  # max_len: size; fallback Pt(20)
NAME_COLOR = RGBColor(0x33, 0x33, 0x33)
SUB_COLOR = RGBColor(0x80, 0x80, 0x80)
LINE_COLOR = RGBColor(0xC0, 0xC0, 0xC0)
LINE_WIDTH = Pt(0.5)
TEXT_BLOCK_HEIGHT_MM = 38


def load_names_from_csv(csv_path):
    """Load names from CSV (expects '様付き' column or '表示名' column)."""
    names = []
    with open(csv_path, encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if '様付き' in row:
                names.append(row['様付き'])
            elif '表示名' in row:
                names.append(f'{row["表示名"]}様')
    return names


def load_names_from_txt(txt_path):
    """Load names from plain text file (one name per line, 様 appended if missing)."""
    names = []
    with open(txt_path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                names.append(line if line.endswith('様') else f'{line}様')
    return names


def name_font_size(name):
    """Pick font size based on name length."""
    for max_len, size in sorted(NAME_FONT_SIZES.items()):
        if len(name) <= max_len:
            return size
    return Pt(20)


def add_separator_lines(slide):
    """Add gray separator lines between card cells."""
    # Vertical center line
    x = Mm(CARD_WIDTH)
    c = slide.shapes.add_connector(1, x, Mm(0), x, Mm(A4_HEIGHT))
    c.line.color.rgb = LINE_COLOR
    c.line.width = LINE_WIDTH
    # Horizontal lines between rows
    for row in range(1, ROWS):
        y = Mm(row * CARD_HEIGHT)
        c = slide.shapes.add_connector(1, Mm(0), y, Mm(A4_WIDTH), y)
        c.line.color.rgb = LINE_COLOR
        c.line.width = LINE_WIDTH


def create_placecards(names, output_pptx, welcome=WELCOME_TEXT, date=DATE_TEXT, font=FONT_NAME):
    """Generate the .pptx place-card file."""
    prs = Presentation()
    prs.slide_width = Mm(A4_WIDTH)
    prs.slide_height = Mm(A4_HEIGHT)

    text_top_offset = (CARD_HEIGHT - TEXT_BLOCK_HEIGHT_MM) / 2
    num_pages = math.ceil(len(names) / CARDS_PER_PAGE)

    for page in range(num_pages):
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
        add_separator_lines(slide)

        for slot in range(CARDS_PER_PAGE):
            idx = page * CARDS_PER_PAGE + slot
            if idx >= len(names):
                break

            name = names[idx]
            col = slot % COLS
            row = slot // COLS

            left = Mm(col * CARD_WIDTH)
            top = Mm(row * CARD_HEIGHT + text_top_offset)
            width = Mm(CARD_WIDTH)
            height = Mm(TEXT_BLOCK_HEIGHT_MM)

            txBox = slide.shapes.add_textbox(left, top, width, height)
            tf = txBox.text_frame
            tf.word_wrap = True

            # Welcome line
            p = tf.paragraphs[0]
            p.alignment = PP_ALIGN.CENTER
            p.space_before = Pt(0)
            p.space_after = Pt(6)
            run = p.add_run()
            run.text = welcome
            run.font.name = font
            run.font.size = WELCOME_FONT_SIZE
            run.font.color.rgb = SUB_COLOR

            # Name line
            p = tf.add_paragraph()
            p.alignment = PP_ALIGN.CENTER
            p.space_before = Pt(0)
            p.space_after = Pt(6)
            run = p.add_run()
            run.text = name
            run.font.name = font
            run.font.size = name_font_size(name)
            run.font.color.rgb = NAME_COLOR

            # Date line
            p = tf.add_paragraph()
            p.alignment = PP_ALIGN.CENTER
            p.space_before = Pt(0)
            p.space_after = Pt(0)
            run = p.add_run()
            run.text = date
            run.font.name = font
            run.font.size = DATE_FONT_SIZE
            run.font.color.rgb = SUB_COLOR

    prs.save(str(output_pptx))
    return num_pages


def convert_to_pdf(pptx_path):
    """Convert .pptx to PDF using LibreOffice."""
    outdir = str(Path(pptx_path).parent)
    result = subprocess.run(
        ['libreoffice', '--headless', '--convert-to', 'pdf', str(pptx_path), '--outdir', outdir],
        capture_output=True, text=True,
    )
    pdf_path = Path(pptx_path).with_suffix('.pdf')
    if pdf_path.exists():
        return pdf_path
    print(f'Warning: PDF conversion may have failed.\n{result.stderr}', file=sys.stderr)
    return None


def main():
    parser = argparse.ArgumentParser(description='Create place cards (席札) from a name list')
    parser.add_argument('input', help='CSV file (from extract_guests.py) or plain text file with names')
    parser.add_argument('-o', '--output', default=None, help='Output .pptx path (default: 席札_placecards.pptx in same dir)')
    parser.add_argument('--welcome', default=WELCOME_TEXT, help=f'Welcome text (default: {WELCOME_TEXT})')
    parser.add_argument('--date', default=DATE_TEXT, help=f'Date text (default: {DATE_TEXT})')
    parser.add_argument('--font', default=FONT_NAME, help=f'Font name (default: {FONT_NAME})')
    parser.add_argument('--no-pdf', action='store_true', help='Skip PDF conversion')
    args = parser.parse_args()

    input_path = Path(args.input)
    if input_path.suffix == '.csv':
        names = load_names_from_csv(input_path)
    else:
        names = load_names_from_txt(input_path)

    if not names:
        print('No names found in input file.', file=sys.stderr)
        sys.exit(1)

    output_pptx = Path(args.output) if args.output else input_path.parent / '席札_placecards.pptx'
    num_pages = create_placecards(names, output_pptx, welcome=args.welcome, date=args.date, font=args.font)
    print(f'Created {output_pptx} ({len(names)} names, {num_pages} pages)')

    if not args.no_pdf:
        pdf_path = convert_to_pdf(output_pptx)
        if pdf_path:
            print(f'Created {pdf_path}')


if __name__ == '__main__':
    main()
